export const FETCH_END = 'setFilms'
export const FETCH_START = 'setLoading'
export const PURGE_AUTH = 'logOut'
export const SET_FILM = 'setFilm'
export const SET_AUTH = 'setUser'
export const SET_COMMENTS = 'setComments'
export const SET_ERROR = 'setError'
export const SET_PROFILE = 'setProfile'
export const SET_GENRES = 'setGenres'

export const RESET_STATE = 'resetModuleState'
